# Keras Basics

Welcome to the section on deep learning! We'll be using Keras with a TensorFlow backend to perform our deep learning operations.

In [1]:
import numpy as np
from numpy import genfromtxt


## Reading in the Data Set

In [2]:
data = genfromtxt('../DATA/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
labels = data[:,4]

In [5]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:, 0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features
y = labels

## Split the Data into Training and Test

Its time to split the data into a train/test set. Keep in mind, sometimes people like to split 3 ways, train/test/validation. We'll keep things simple for now. **Remember to check out the video explanation as to why we split and what all the parameters mean!**

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

## Standardizing the Data

Usually when using Neural Networks, you will get better performance when you standardize the data. Standardization just means normalizing the values to all fit between a certain range, like 0-1, or -1 to 1.

The scikit learn library also provides a nice function for this.

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
scaler_object = MinMaxScaler()

In [14]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
scale_X_train = scaler_object.transform(X_train)

In [16]:
scale_X_test = scaler_object.transform(X_test)

## Building the Network with Keras

Let's build a simple neural network!

In [18]:
from keras.models import Sequential
from keras.layers import Dense

In [22]:
model = Sequential()
model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu')) # hidden layers
model.add(Dense(1, activation='sigmoid'))


### Compile Model

In [24]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

## Fit (Train) the Model

In [25]:
model.fit(scale_X_train, y_train,epochs=50, verbose=2)

Epoch 1/50
 - 0s - loss: 0.6895 - acc: 0.5223
Epoch 2/50
 - 0s - loss: 0.6694 - acc: 0.7160
Epoch 3/50
 - 0s - loss: 0.6480 - acc: 0.6366
Epoch 4/50
 - 0s - loss: 0.6321 - acc: 0.6246
Epoch 5/50
 - 0s - loss: 0.6154 - acc: 0.6540
Epoch 6/50
 - 0s - loss: 0.5976 - acc: 0.7225
Epoch 7/50
 - 0s - loss: 0.5771 - acc: 0.7693
Epoch 8/50
 - 0s - loss: 0.5565 - acc: 0.7965
Epoch 9/50
 - 0s - loss: 0.5353 - acc: 0.8009
Epoch 10/50
 - 0s - loss: 0.5146 - acc: 0.8052
Epoch 11/50
 - 0s - loss: 0.4946 - acc: 0.8270
Epoch 12/50
 - 0s - loss: 0.4765 - acc: 0.8324
Epoch 13/50
 - 0s - loss: 0.4582 - acc: 0.8390
Epoch 14/50
 - 0s - loss: 0.4413 - acc: 0.8455
Epoch 15/50
 - 0s - loss: 0.4253 - acc: 0.8575
Epoch 16/50
 - 0s - loss: 0.4115 - acc: 0.8618
Epoch 17/50
 - 0s - loss: 0.3966 - acc: 0.8683
Epoch 18/50
 - 0s - loss: 0.3825 - acc: 0.8760
Epoch 19/50
 - 0s - loss: 0.3706 - acc: 0.8847
Epoch 20/50
 - 0s - loss: 0.3564 - acc: 0.8857
Epoch 21/50
 - 0s - loss: 0.3448 - acc: 0.8879
Epoch 22/50
 - 0s - lo

## Predicting New Unseen Data


In [27]:
# model.predict_classes(scale_X_test)

# Evaluating Model Performance

So how well did we do? How do we actually measure "well". Is 95% accuracy good enough? It all depends on the situation. Also we need to take into account things like recall and precision. Make sure to watch the video discussion on classification evaluation before running this code!

In [28]:
model.metrics_names

['loss', 'acc']

In [29]:
from sklearn.metrics import confusion_matrix, classification_report

In [30]:
predictions = model.predict_classes(scale_X_test)

In [31]:
confusion_matrix(y_test,predictions)

array([[253,   4],
       [ 15, 181]])

In [32]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.94      0.98      0.96       257
        1.0       0.98      0.92      0.95       196

avg / total       0.96      0.96      0.96       453



## Saving and Loading Models

Now that we have a model trained, let's see how we can save and load it.

In [33]:
model.save('mymodel.h5')

In [34]:
from keras.models import load_model

In [35]:
newmodel = load_model('mymodel.h5')

In [36]:
newmodel.predict_classes(scale_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    